FROM golang:1.20-alpine as build

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./

RUN go mod download && go mod verify

COPY . .

# build all the packages in the current directory and its subdirectories
RUN go build -o /usr/local/bin/app ./...

FROM docker:23.0.6-dind-alpine3.18 as runtime

RUN apk add --no-cache bash

COPY ./start.sh /start.sh

RUN chmod +x /start.sh

COPY --from=build /usr/local/bin/app /app

WORKDIR /

ENTRYPOINT ["bash", "/start.sh" ]
